application.name=SYSRMS

# Logging
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p traceId=%X{traceId}, spanId=%X{spanId}, sampled=%X{sampled} [%c] (%t) %s%e%n

application.domain=/SYS/RMS
application.domain.version=31

ddc-base-stored-topic=ddc-base-stored-sys.rms

%dev.requirements-machine-id=SYS.RMS.Requirement
quarkus.kubernetes.env.mapping.requirements-machine-id.from-configmap=sysrms-settings
quarkus.kubernetes.env.mapping.requirements-machine-id.with-key=requirements-machine-id

#fault tolerance
quarkus.kubernetes.strategy=rolling-update
quarkus.kubernetes.rolling-update.max-surge=25%
quarkus.kubernetes.rolling-update.max-unavailable=25%

# Datasource
%dev.quarkus.datasource.jdbc.url=jdbc:h2:file:./target/h2db/db/sysrms;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE
%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.username=SYSRMS
%dev.quarkus.datasource.password=
%dev.quarkus.http.port=8092
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/SYSRMS
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=SYSRMS
%prod.quarkus.datasource.password=
%prod.quarkus.hibernate-orm.database.default-schema=sysrms
%prod.quarkus.liquibase.default-schema-name=sysrms
%prod.quarkus.liquibase.liquibase-schema-name=sysrms
%prod.quarkus.liquibase.database-change-log-lock-table-name=liquibase_lock
%prod.quarkus.liquibase.database-change-log-table-name=liquibase_log
quarkus.datasource.jdbc.max-size=64
quarkus.datasource.jdbc.min-size=8
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.sql-load-script=no-file
quarkus.hibernate-orm.implicit-naming-strategy=com.colvir.ms.generated.svc.base.config.hibernate.JHipsterCompatibleImplicitNamingStrategy
quarkus.hibernate-orm.physical-naming-strategy=com.colvir.ms.generated.svc.base.config.hibernate.JHipsterCompatiblePhysicalNamingStrategy
quarkus.hibernate-orm.second-level-caching-enabled=false
%test.quarkus.hibernate-orm.second-level-caching-enabled=false

%test.info-service-api/mp-rest/url=http://localhost:8082
# Router agent extension
%test.rest-client.use-internal-address=false
%test.rest-client.gateway-url=localhost:8082
%test.rest-client.use-https=false
# Hierarchy extension
%test.quarkus.rest-client.ddc-info-service.url=http://localhost:8082

quarkus.http.test-port=8083

quarkus.liquibase.change-log=config/liquibase/master.xml
quarkus.liquibase.migrate-at-start=true
quarkus.datasource.jdbc.new-connection-sql=CREATE SCHEMA IF NOT EXISTS sysrms;

# Use DevServices
%test.quarkus.datasource.db-kind=postgresql
%test.quarkus.hibernate-orm.database.generation=validate
%test.quarkus.hibernate-orm.database.default-schema=sysrms
%test.quarkus.liquibase.default-schema-name=sysrms
%test.quarkus.liquibase.liquibase-schema-name=sysrms
%test.quarkus.liquibase.database-change-log-lock-table-name=liquibase_lock
%test.quarkus.liquibase.database-change-log-table-name=liquibase_log

%dev.quarkus.hibernate-orm.database.generation=none
%dev.quarkus.hibernate-orm.database.default-schema=sysrms
%dev.quarkus.liquibase.default-schema-name=sysrms
%dev.quarkus.liquibase.liquibase-schema-name=sysrms
%dev.quarkus.liquibase.database-change-log-lock-table-name=liquibase_lock
%dev.quarkus.liquibase.database-change-log-table-name=liquibase_log

# TODO: remove after upgrade sysopr
%test.sysopr.tarantool.queue.server.address=localhost:3301
%test.sysopr.tarantool.queue.server.user=guest
%test.sysopr.tarantool.queue.server.password=
%test.sysopr.tarantool.journal.server.address=localhost:3301
%test.sysopr.tarantool.journal.server.user=guest
%test.sysopr.tarantool.journal.server.password=



quarkus.mailer.from=sysrms@localhost
quarkus.mailer.host=localhost
quarkus.mailer.port=25
quarkus.mailer.ssl=false
quarkus.mailer.username=
quarkus.mailer.password=

quarkus.micrometer.export.prometheus.enabled=true

quarkus.jackson.serialization-inclusion=non_null

quarkus.smallrye-health.root-path=/sysrms//management/health
quarkus.micrometer.export.prometheus.path=/sysrms//management/prometheus

quarkus.http.root-path=/sysrms/

quarkus.smallrye-openapi.path=/sysrms/v2/api-docs
quarkus.swagger-ui.path=/sysrms/swagger-ui
quarkus.swagger-ui.always-include=true

quarkus.jib.jvm-arguments=-Xmx1024m
quarkus.jib.native-arguments=-Xmx256m

# OAuth 2.0 and OIDC
quarkus.oidc.enabled=true
quarkus.oidc.auth-server-url=http://localhost:9080/auth/realms/jhipster/
%dev.quarkus.oidc.client-id=web_app
%dev.quarkus.oidc.credentials.secret=web_app
%test.quarkus.oidc.credentials.secret=web_app
quarkus.oidc.application-type=hybrid
quarkus.oidc.token.issuer=any
quarkus.oidc.authentication.scopes=profile,address,email,address,phone,offline_access
quarkus.oidc.authentication.cookie-path=/
quarkus.oidc.authentication.redirect-path=/login/oauth2/code/oidc
quarkus.oidc.authentication.restore-path-after-redirect=false

%test.quarkus.oidc.client-id=dummy
%test.quarkus.oidc.application-type=service

## DF: securityContext
quarkus.kubernetes.security-context.run-as-user=65534
quarkus.kubernetes.security-context.run-as-non-root=true
quarkus.kubernetes.security-context.allow-privilege-escalation=false

## DF: switch base image from ubi to ecplipse-temurin
quarkus.jib.base-jvm-image=nexus.colvir.ru/df/eclipse-temurin:21.0.9_10-jdk-alpine-3.23

## DF: disable version change in selector (errror: field is immutable)
quarkus.kubernetes.add-version-to-label-selectors=false
quarkus.kubernetes.add-version-to-labels=false
##
quarkus.kubernetes.ports.http.host-port=8080
quarkus.kubernetes.namespace=dev-services
quarkus.kubernetes.image-pull-secrets=colvir-nexus-registry
quarkus.container-image.registry=nexus.colvir.ru
quarkus.container-image.group=fb-dev-applications
quarkus.container-image.name=sysrms
quarkus.container-image.additional-tags=latest

quarkus.kubernetes.externalize-init=false

quarkus.kubernetes.labels.ddc-object=sysrms
quarkus.kubernetes.startup-probe.failure-threshold=30
quarkus.kubernetes.startup-probe.initial-delay=20s
quarkus.kubernetes.startup-probe.period=10s
quarkus.kubernetes.startup-probe.timeout=1s

quarkus.kubernetes.env.mapping.quarkus-http-cors.from-configmap=application-config
quarkus.kubernetes.env.mapping.quarkus-http-cors.with-key=cors-enabled
quarkus.kubernetes.env.mapping.kafka-bootstrap-servers.from-configmap=services-endpoints
quarkus.kubernetes.env.mapping.kafka-bootstrap-servers.with-key=kafka
quarkus.kubernetes.env.mapping.quarkus-redis-hosts.from-configmap=services-endpoints
quarkus.kubernetes.env.mapping.quarkus-redis-hosts.with-key=redis
quarkus.kubernetes.env.mapping.quarkus-rest-client-ddc-router-url.from-configmap=services-endpoints
quarkus.kubernetes.env.mapping.quarkus-rest-client-ddc-router-url.with-key=ddc-router
quarkus.kubernetes.env.mapping.router-url.from-configmap=services-endpoints
quarkus.kubernetes.env.mapping.router-url.with-key=ddc-router
%dev.router-url=https://fb-router-core-banking.colvir.ru
quarkus.rest-client.router-api.url=${router-url}
quarkus.kubernetes.env.mapping.quarkus-rest-client-ddc-info-service-url.from-configmap=services-endpoints
quarkus.kubernetes.env.mapping.quarkus-rest-client-ddc-info-service-url.with-key=ddc-info-service

# postgres
quarkus.kubernetes.env.mapping.quarkus-datasource-jdbc-url.from-secret=services-postgresql
quarkus.kubernetes.env.mapping.quarkus-datasource-jdbc-url.with-key=services-postgresql-sysrms-jdbc-url
quarkus.kubernetes.env.mapping.quarkus-datasource-username.from-secret=services-postgresql
quarkus.kubernetes.env.mapping.quarkus-datasource-username.with-key=services-postgresql-username
quarkus.kubernetes.env.mapping.quarkus-datasource-password.from-secret=services-postgresql
quarkus.kubernetes.env.mapping.quarkus-datasource-password.with-key=services-postgresql-password

# keycloak
quarkus.kubernetes.env.mapping.quarkus-oidc-auth-server-url.from-secret=keycloak-secret
quarkus.kubernetes.env.mapping.quarkus-oidc-auth-server-url.with-key=keycloak-auth-url
quarkus.kubernetes.env.mapping.quarkus-oidc-client-id.from-secret=keycloak-secret
quarkus.kubernetes.env.mapping.quarkus-oidc-client-id.with-key=keycloak-oidc-client-id
quarkus.kubernetes.env.mapping.quarkus-oidc-credentials-secret.from-secret=keycloak-secret
quarkus.kubernetes.env.mapping.quarkus-oidc-credentials-secret.with-key=keycloak-oidc-credentials-secret

# Kafka
quarkus.kubernetes.env.secrets=kafka-credentials

# OpenTelemetry
%dev.quarkus.otel.sdk.disabled=true
quarkus.otel.service.name=${quarkus.application.name}.${quarkus.kubernetes.namespace}
quarkus.otel.traces.sampler.arg=1.0
quarkus.otel.exporter.otlp.traces.timeout=30S
quarkus.otel.exporter.otlp.traces.protocol=grpc
quarkus.otel.traces.sampler=custom-otel-sampler
quarkus.kubernetes.env.mapping.quarkus_otel_exporter_otlp_traces_endpoint.from-configmap=opentelemetry-config
quarkus.kubernetes.env.mapping.quarkus_otel_exporter_otlp_traces_endpoint.with-key=otel_exporter_otlp_traces_endpoint
quarkus.kubernetes.env.mapping.quarkus_otel_sdk_disabled.from-configmap=opentelemetry-config
quarkus.kubernetes.env.mapping.quarkus_otel_sdk_disabled.with-key=otel_sdk_disabled
#quarkus.kubernetes.env.mapping.quarkus_datasource_jdbc_telemetry.from-configmap=opentelemetry-config
#quarkus.kubernetes.env.mapping.quarkus_datasource_jdbc_telemetry.with-key=datasource_jdbc_telemetry
quarkus.datasource.jdbc.telemetry=true

quarkus.kubernetes.prometheus.generate-service-monitor=false
quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG
